### PR TITLE
WIP: Humidifier Dehumidifier

### LINKED ISSUE #323: Humidifier/dehumidifier support
It would be nice if the support for 8.19 Humidifier Dehumidifier (page 144 of the spec) was present.
I am not comfortable enough with nodeJS/HomeBridge plug-ins but I could have a look…

### PR DESCRIPTION
**Pull request by eutampieri**
Attempts to close #323 
I am not sure to have done everything correctly, but I added the missing characteristics and updated the configuration parsing logic to accomodate the new service.
I don't know if there's something else to be done, so I'm waiting your feedback

### CODE REVIEW

**Comment by arachnetech** [comment]
That looks good to me. I tend to add limiting functionality when someone asks for them.  Are their specific dehumidifier settings that you think need user-controlled limits?

**Comment by eutampieri** [comment]
I don’t know, also looking to other PRs I think there's some stuff missing

**Comment by eutampieri** [comment]
Also, I don’t know about the limits, what do you mean?

**Comment by eutampieri** [comment]
Yes, speaking of limits I own a dehumidifier only device so it would be handy if I could tell mqttthings that it’s only a dehumidifier and not an humidifier

**Comment by arachnetech** [comment]
You said "I'm not sure about limiting the device status (as in the Heater cooler)" - I don't think any of dehumidifier's settings need limiting in this way. I haven't tested it, but just reading the code I think it can be merged. However, it would be great if you could add it to `docs/Accessories.md` first.

**Comment by arachnetech** [comment]
Ah, you're right - you don't have `characteristic_CurrentHumidifierDehumidifierState` or `characteristic_TargetHumidifierDehumidifierState` defined! It's in the target state that you could limit it to be just a dehumidifier.

If you're stuck I'm happy to take over and try to fill in the gaps?

**Comment by eutampieri** [comment]
No, I’m not stuck, I’ve only little time to work on this feature

**Comment by eutampieri** [comment]
(Or at least I think I’m not stuck). In my previous comment I was asking guidance on how to implement a parameter to expose only the dehumidifier (or humidifier) characteristic

**Comment by arachnetech** [comment]
Thanks, I understand!

Ok, once you've written the target state characteristic let me know and I can help with the limiting.

**Comment by tom-23** [comment]
@arachnetech do you know when you plan to release this? Been stuck using the "airPurifier" type and was wondering when I could use this instead.

**Comment by arachnetech** [comment]
@eutampieri Hasn't had time to finish implementing it yet, unfortunately - and I haven't had time to offer to take over either.

**Comment by eutampieri** [comment]
I hope to get some work done on October. In the meantime, I’ll close this

**Comment by raphaeleduardo42** [comment]
homebridge-ewelink updated a Simulation implementing a Humidifier/Dehumidifier by using a Sonoff TH10/TH16 (switch with RH sensor), maybe this could help with somehow.

[https://github.com/bwp91/homebridge-ewelink/wiki/1-Humidifier-(with-Sonoff-TH10-or-TH16)](1 Humidifier (with Sonoff TH10 or TH16)

**Comment by rcaceiro** [comment]
Any updates on this?
There is no MQTT dehumidifier plugin to homebridge

**Pull request closed without merging**
