### PR TITLE
Add 'service' to the info provided to CODECs

### LINKED ISSUE #317: Codecs and "custom" accessories
A codec is installed at the "accessory" level and a "custom" accessory allows for grouping of multiple services.  It would be helpful when a codec is invoked for a property service in a "custom" grouping to know its service details (name/type) so that the codec can use that information to make decisions.  This stems from multiple get properties using the same topic for results with tasmota, but I think the ability to disambiguate in the codec would be useful no matter.

### PR DESCRIPTION
**Pull request by tevans62**
Fixes #317 

In a "custom" accessory, there is a collection of accessories listed in the 'services' section.

This change adds the particular accessory to "info" for the decode and encode methods of a CODEC, allowing disambiguation when the multiple accessories use the same topic.

### CODE REVIEW

**Comment by arachnetech** [comment]
I'm a bit confused by this. You appear to be passing the Homebridge Service through every publish/subscribe function to the codec context. Is this really what you want? Your description mentions the mqtt-thing accessory type of the 'service' sub-accessory within "services" - but unless I'm mistaken that's not what you're doing.

I think a better solution might be to allow separate codec instances for each sub-accessory of a 'multi' accessory?

**Comment by tevans62** [comment]
> I'm a bit confused by this. You appear to be passing the Homebridge Service through every publish/subscribe function to the codec context. Is this really what you want?

This is what I wanted in this instance, yes - the service though is only the instance for the accessory, so if a single accessory, the encode/decode receives that.

If it is a "custom", every encode/decode receives the "service" entry from the array so that that on a subscribe, for instance, the receiver know that the result is from a particular control and on a publish it can know what control is being operated.

The genesis for this a device I am trying to control is a tuya-based control with the ESP32 connected via serial to another MCU that does the work.  All operations are done via generic serial send type publish operations and the 'results' always come back on the same topic.

I am modeling the various modes of the device via a series of switches, mutually exclusive in that only one came be on.
With this additional information one can programmatically determine the mode in use and keep a shared copy of the MCU state to deliver on all publish operations. 

 Your description mentions the mqtt-thing accessory type of the 'service' sub-accessory within "services" - but unless I'm mistaken that's not what you're doing.
> 
> I think a better solution might be to allow separate codec instances for each sub-accessory of a 'multi' accessory?

I considered this as well and while I think it is an equal manner to achieve the desired functionality, for the situation I described above, distributions the state shared among 8 "mode" buttons across 8 CODECs (or the same one I guess via the global state?) seemed excessive.  Being able to manage all that state in one CODEC makes it easier (imho) to grok the behavior of the entire device from one CODEC.

The device I am working on is not ready for primetime but I would be happy to share it with you to see if I am just missing some basic understanding of mqttthing (which I am having a lot of fun with, btw).

**Comment by arachnetech** [comment]
Sorry, been busy and not had a chance to come back to you on this. I'm still not sure I understand the purpose of this correctly. Are you able to share a config and codec showing how you're using it?

What's really confusing me is that you say _every encode/decode receives the "service" entry from the array_, but it's not the service entry from the configured array of services that you're passing through as far as I can tell, but the service that you're passing in to mqttPublish (e.g. in `integerCharacteristic`) is a Homebridge service instance, not the service entry from the configuration array.

**Comment by arachnetech** [comment]
Closing a conflicts now.

**Pull request closed without merging**
