### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by zazula**
Send service names to HomeKit using the ConfiguredName characteristic.

We could also watch for name changes in HomeKit and store them but I didn't see a clear path to that.  Something like:

service.getCharacteristic(Characteristic.ConfiguredName)
    .onSet(/* store the new name */);

### CODE REVIEW

**Comment by zazula** [comment]
Thanks for listening.  Without this change, all services have the name given to the accessory at the top level, e.g., 
```
{
  accessory: "mqttthing",
  name: <<<< this field
  ...
}

```
With this change, each service gets the individual name specified along with it, e.g., 

```
{
  accessory: "mqttthing",
  name: "big daddy",
  ...
  "services" : [
    type: "motionsensor",
    name: <<<< this field
  ...
}

```

**Comment by arachnetech** [comment]
Thanks, I understand. Sorry it's taken me so long to get around to merging, incidentally - work has been even busier than usual and I just haven't made time for mqttthing!

**Comment by arachnetech** [comment]
Is there anything that we can do to fix https://github.com/arachnetech/homebridge-mqttthing/issues/656? Perhaps your new behaviour needs to be optional, enabled by another configuration setting?

**Comment by zazula** [comment]
> Is there anything that we can do to fix #656? Perhaps your new behaviour needs to be optional, enabled by another configuration setting?

Yes, we can watch for 'onSet' of 'Characteristic.ConfiguredName' on all services and write out an updated config file.  The homebridge API package includes a method for this:

https://www.jsdocs.io/package/homebridge#API.updatePlatformAccessories

However, I looked and don't see an existing code path that writes out the config file currently.

Also, we'd want to handle changes to any of the derived names (e.g., speakers and inputs in a 'television' service).

**Pull request merged**
