### PR TITLE
Typo - Just realized I can't test the ToC link easily

### PR DESCRIPTION
**Pull request by NorthernMan54**

### CODE REVIEW

**Comment by arachnetech** [comment]
Oops, I missed that too!

**Comment by NorthernMan54** [comment]
I was watching it, looking to see other peoples config’s and get some more ideas for mine and kept thinking why is it empty ;-(

Have you thought about having a simplified config?   With my plugins I try to use device discovery and auto config based on the device details supplied?   Most of mine have just a one or two line config.

It would mean that unknown devices would not auto configure, but should be easy to create a simple table to map features to services and characteristics.  Then adding a similar device would be just updating the table.

**Comment by arachnetech** [comment]
I've been thinking of adding an option to use JSON for the MQTT payload (with one command topic and one state topic, sharing the same JSON format) rather than multiple MQTT topics - which would certainly simplify the configuration significantly. I have also considered adding support for specific devices - but currently mine are all bespoke. I'd also like to release open source ESP8266 code that people could use (or base their code on).

I do like the idea of some kind of auto-discovery. It would be possible either to adopt an "autoconfig works like this" approach, making auto-configured devices less flexible than individually-configured devices, or perhaps to define templates which could then be applied to multiple devices. However, even with my 615 line homebridge configuration file (most of which is mqttthing devices!) it's really not hard finding devices and copying and pasting to add new devices in a text editor.

As always, and with all these things, my problem is finding the time to do it! I only created mqttthing for my own personal use initially.

**Comment by NorthernMan54** [comment]
I was thinking about auto-discover and configure more and am thinking that with the Sonoff-Tasmota ecosystem, and the wide variety of devices it may be hard to achieve, as you would always have devices needing manual configuration.  So the config.json would only need to include the manually configured devices.

615 lines of config, wow, editing that must be like heart surgery or something.  I shouldn’t talk though, as I probably have the same, except it is split across almost a dozen homebridge instances.  I have almost a hundred devices, with about a dozen different devices, spread across 2 houses.

But with that said, I feel your comment about time to do things, balanced against other activities.  For me I’m doing this just to gain WAF points, and find anything outside of that is not a good use of my time.

**Pull request merged**
