### PR TITLE
Easy Config for Config-UI-X

### PR DESCRIPTION
**Pull request by donavanbecker**
@arachnetech  added easy config for [config-ui-x](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI).

It is not totally complete. but figured I could get you started.

### CODE REVIEW

**Comment by arachnetech** [comment]
Thanks. Bizarrely, I knew nothing about these schemas until Sunday, when I started looking at writing a schema for HOOBS' configuration interface.

**Comment by donavanbecker** [comment]
@oznu has a really good wiki for this and his for UI x is all set with the plugin type of accessory or platform.

**Comment by arachnetech** [comment]
Any tips on getting config-ui-x to 'see' the schema of a development mqttthing? (I run it using the `run.sh` script.)

**Comment by donavanbecker** [comment]
@arachnetech did ozno answer your question on slack?

**Comment by arachnetech** [comment]
Yes, very helpful. Thanks.

**Pull request merged**
